#!/bin/bash
# Ask the user for their name
echo "HOMEBREW_PG_DBNAME?"
read HOMEBREW_PG_DBNAME

echo "HOMEBREW_PG_USER?"
read HOMEBREW_PG_USER

echo "HOMEBREW_PG_PASS?"
read HOMEBREW_PG_PASS

echo "HOMEBREW_PG_ADDRESS?"
read HOMEBREW_PG_ADDRESS

echo "COMBO_PG_DBNAME?"
read COMBO_PG_DBNAME

echo "COMBO_PG_USER?"
read COMBO_PG_USER

echo "COMBO_PG_PASS?"
read COMBO_PG_PASS

echo "COMBO_PG_ADDRESS?"
read COMBO_PG_ADDRESS

echo "export HOMEBREW_PG_DBNAME=$HOMEBREW_PG_DBNAME"
echo "export HOMEBREW_PG_USER=$HOMEBREW_PG_USER"
echo "export HOMEBREW_PG_PASS=$HOMEBREW_PG_PASS"
echo "export HOMEBREW_PG_ADDRESS=$HOMEBREW_PG_ADDRESS"

echo "export COMBO_PG_DBNAME=$COMBO_PG_DBNAME"
echo "export COMBO_PG_USER=$COMBO_PG_USER"
echo "export COMBO_PG_PASS=$COMBO_PG_PASS"
echo "export COMBO_PG_ADDRESS=$COMBO_PG_ADDRESS"




